# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "0.8.0"

[[constraint]]
  name = "github.com/containernetworking/plugins"
  version = "0.8.7"

[[constraint]]
  name = "github.com/coreos/go-iptables"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/d2g/dhcp4"

[[constraint]]
  branch = "master"
  name = "github.com/d2g/dhcp4client"

[[constraint]]
  branch = "master"
  name = "github.com/denverdino/aliyungo"

[[constraint]]
  branch = "master"
  name = "github.com/j-keck/arping"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  branch = "master"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "github.com/docker/docker"
  source = "github.com/docker/engine"
  branch = "18.06"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true