// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rpc.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IPType int32

const (
	IPType_TypeVPCIP      IPType = 0
	IPType_TypeVPCENI     IPType = 1
	IPType_TypeENIMultiIP IPType = 2
)

// Enum value maps for IPType.
var (
	IPType_name = map[int32]string{
		0: "TypeVPCIP",
		1: "TypeVPCENI",
		2: "TypeENIMultiIP",
	}
	IPType_value = map[string]int32{
		"TypeVPCIP":      0,
		"TypeVPCENI":     1,
		"TypeENIMultiIP": 2,
	}
)

func (x IPType) Enum() *IPType {
	p := new(IPType)
	*p = x
	return p
}

func (x IPType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[0].Descriptor()
}

func (IPType) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[0]
}

func (x IPType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPType.Descriptor instead.
func (IPType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

type Error int32

const (
	Error_ErrNoErr       Error = 0
	Error_ErrCRDNotFound Error = 1
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "ErrNoErr",
		1: "ErrCRDNotFound",
	}
	Error_value = map[string]int32{
		"ErrNoErr":       0,
		"ErrCRDNotFound": 1,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[1].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[1]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

type EventTarget int32

const (
	EventTarget_EventTargetNode EventTarget = 0
	EventTarget_EventTargetPod  EventTarget = 1
)

// Enum value maps for EventTarget.
var (
	EventTarget_name = map[int32]string{
		0: "EventTargetNode",
		1: "EventTargetPod",
	}
	EventTarget_value = map[string]int32{
		"EventTargetNode": 0,
		"EventTargetPod":  1,
	}
)

func (x EventTarget) Enum() *EventTarget {
	p := new(EventTarget)
	*p = x
	return p
}

func (x EventTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[2].Descriptor()
}

func (EventTarget) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[2]
}

func (x EventTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventTarget.Descriptor instead.
func (EventTarget) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

type EventType int32

const (
	EventType_EventTypeNormal  EventType = 0
	EventType_EventTypeWarning EventType = 1
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EventTypeNormal",
		1: "EventTypeWarning",
	}
	EventType_value = map[string]int32{
		"EventTypeNormal":  0,
		"EventTypeWarning": 1,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[3].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[3]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

// IPSet declare a string set contain v4 v6 info
type IPSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPv4          string                 `protobuf:"bytes,1,opt,name=IPv4,proto3" json:"IPv4,omitempty"`
	IPv6          string                 `protobuf:"bytes,2,opt,name=IPv6,proto3" json:"IPv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPSet) Reset() {
	*x = IPSet{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPSet) ProtoMessage() {}

func (x *IPSet) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPSet.ProtoReflect.Descriptor instead.
func (*IPSet) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *IPSet) GetIPv4() string {
	if x != nil {
		return x.IPv4
	}
	return ""
}

func (x *IPSet) GetIPv6() string {
	if x != nil {
		return x.IPv6
	}
	return ""
}

type AllocIPRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	K8SPodName             string                 `protobuf:"bytes,1,opt,name=K8sPodName,proto3" json:"K8sPodName,omitempty"`
	K8SPodNamespace        string                 `protobuf:"bytes,2,opt,name=K8sPodNamespace,proto3" json:"K8sPodNamespace,omitempty"`
	K8SPodInfraContainerId string                 `protobuf:"bytes,3,opt,name=K8sPodInfraContainerId,proto3" json:"K8sPodInfraContainerId,omitempty"`
	Netns                  string                 `protobuf:"bytes,4,opt,name=Netns,proto3" json:"Netns,omitempty"`
	IfName                 string                 `protobuf:"bytes,5,opt,name=IfName,proto3" json:"IfName,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AllocIPRequest) Reset() {
	*x = AllocIPRequest{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocIPRequest) ProtoMessage() {}

func (x *AllocIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocIPRequest.ProtoReflect.Descriptor instead.
func (*AllocIPRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *AllocIPRequest) GetK8SPodName() string {
	if x != nil {
		return x.K8SPodName
	}
	return ""
}

func (x *AllocIPRequest) GetK8SPodNamespace() string {
	if x != nil {
		return x.K8SPodNamespace
	}
	return ""
}

func (x *AllocIPRequest) GetK8SPodInfraContainerId() string {
	if x != nil {
		return x.K8SPodInfraContainerId
	}
	return ""
}

func (x *AllocIPRequest) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *AllocIPRequest) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

type NetConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasicInfo     *BasicInfo             `protobuf:"bytes,1,opt,name=BasicInfo,proto3" json:"BasicInfo,omitempty"`
	ENIInfo       *ENIInfo               `protobuf:"bytes,2,opt,name=ENIInfo,proto3" json:"ENIInfo,omitempty"`
	Pod           *Pod                   `protobuf:"bytes,3,opt,name=Pod,proto3" json:"Pod,omitempty"`
	IfName        string                 `protobuf:"bytes,4,opt,name=IfName,proto3" json:"IfName,omitempty"`
	ExtraRoutes   []*Route               `protobuf:"bytes,5,rep,name=ExtraRoutes,proto3" json:"ExtraRoutes,omitempty"`
	DefaultRoute  bool                   `protobuf:"varint,6,opt,name=DefaultRoute,proto3" json:"DefaultRoute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetConf) Reset() {
	*x = NetConf{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetConf) ProtoMessage() {}

func (x *NetConf) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetConf.ProtoReflect.Descriptor instead.
func (*NetConf) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *NetConf) GetBasicInfo() *BasicInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

func (x *NetConf) GetENIInfo() *ENIInfo {
	if x != nil {
		return x.ENIInfo
	}
	return nil
}

func (x *NetConf) GetPod() *Pod {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *NetConf) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

func (x *NetConf) GetExtraRoutes() []*Route {
	if x != nil {
		return x.ExtraRoutes
	}
	return nil
}

func (x *NetConf) GetDefaultRoute() bool {
	if x != nil {
		return x.DefaultRoute
	}
	return false
}

type AllocIPReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	IPType        IPType                 `protobuf:"varint,2,opt,name=IPType,proto3,enum=rpc.IPType" json:"IPType,omitempty"`
	IPv4          bool                   `protobuf:"varint,3,opt,name=IPv4,proto3" json:"IPv4,omitempty"`
	IPv6          bool                   `protobuf:"varint,4,opt,name=IPv6,proto3" json:"IPv6,omitempty"`
	NetConfs      []*NetConf             `protobuf:"bytes,5,rep,name=NetConfs,proto3" json:"NetConfs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocIPReply) Reset() {
	*x = AllocIPReply{}
	mi := &file_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocIPReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocIPReply) ProtoMessage() {}

func (x *AllocIPReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocIPReply.ProtoReflect.Descriptor instead.
func (*AllocIPReply) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *AllocIPReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AllocIPReply) GetIPType() IPType {
	if x != nil {
		return x.IPType
	}
	return IPType_TypeVPCIP
}

func (x *AllocIPReply) GetIPv4() bool {
	if x != nil {
		return x.IPv4
	}
	return false
}

func (x *AllocIPReply) GetIPv6() bool {
	if x != nil {
		return x.IPv6
	}
	return false
}

func (x *AllocIPReply) GetNetConfs() []*NetConf {
	if x != nil {
		return x.NetConfs
	}
	return nil
}

type BasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodIP         *IPSet                 `protobuf:"bytes,1,opt,name=PodIP,proto3" json:"PodIP,omitempty"`
	PodCIDR       *IPSet                 `protobuf:"bytes,2,opt,name=PodCIDR,proto3" json:"PodCIDR,omitempty"`     // subnet for pod, value form vSwitch CIDR or podCIDR
	GatewayIP     *IPSet                 `protobuf:"bytes,3,opt,name=GatewayIP,proto3" json:"GatewayIP,omitempty"` // gw for the subnet
	ServiceCIDR   *IPSet                 `protobuf:"bytes,4,opt,name=ServiceCIDR,proto3" json:"ServiceCIDR,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicInfo) Reset() {
	*x = BasicInfo{}
	mi := &file_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicInfo) ProtoMessage() {}

func (x *BasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicInfo.ProtoReflect.Descriptor instead.
func (*BasicInfo) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *BasicInfo) GetPodIP() *IPSet {
	if x != nil {
		return x.PodIP
	}
	return nil
}

func (x *BasicInfo) GetPodCIDR() *IPSet {
	if x != nil {
		return x.PodCIDR
	}
	return nil
}

func (x *BasicInfo) GetGatewayIP() *IPSet {
	if x != nil {
		return x.GatewayIP
	}
	return nil
}

func (x *BasicInfo) GetServiceCIDR() *IPSet {
	if x != nil {
		return x.ServiceCIDR
	}
	return nil
}

type ENIInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MAC           string                 `protobuf:"bytes,1,opt,name=MAC,proto3" json:"MAC,omitempty"`
	Trunk         bool                   `protobuf:"varint,2,opt,name=Trunk,proto3" json:"Trunk,omitempty"` // eni is trunk
	Vid           uint32                 `protobuf:"varint,3,opt,name=Vid,proto3" json:"Vid,omitempty"`     // vlan ID
	GatewayIP     *IPSet                 `protobuf:"bytes,4,opt,name=GatewayIP,proto3" json:"GatewayIP,omitempty"`
	ERDMA         bool                   `protobuf:"varint,5,opt,name=eRDMA,proto3" json:"eRDMA,omitempty"` // eni is eRDMA
	VfId          *uint32                `protobuf:"varint,6,opt,name=VfId,proto3,oneof" json:"VfId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ENIInfo) Reset() {
	*x = ENIInfo{}
	mi := &file_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ENIInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ENIInfo) ProtoMessage() {}

func (x *ENIInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ENIInfo.ProtoReflect.Descriptor instead.
func (*ENIInfo) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ENIInfo) GetMAC() string {
	if x != nil {
		return x.MAC
	}
	return ""
}

func (x *ENIInfo) GetTrunk() bool {
	if x != nil {
		return x.Trunk
	}
	return false
}

func (x *ENIInfo) GetVid() uint32 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *ENIInfo) GetGatewayIP() *IPSet {
	if x != nil {
		return x.GatewayIP
	}
	return nil
}

func (x *ENIInfo) GetERDMA() bool {
	if x != nil {
		return x.ERDMA
	}
	return false
}

func (x *ENIInfo) GetVfId() uint32 {
	if x != nil && x.VfId != nil {
		return *x.VfId
	}
	return 0
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dst           string                 `protobuf:"bytes,1,opt,name=Dst,proto3" json:"Dst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *Route) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

// VETH Basic
type Pod struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ingress         uint64                 `protobuf:"varint,1,opt,name=Ingress,proto3" json:"Ingress,omitempty"`
	Egress          uint64                 `protobuf:"varint,2,opt,name=Egress,proto3" json:"Egress,omitempty"`
	NetworkPriority string                 `protobuf:"bytes,3,opt,name=NetworkPriority,proto3" json:"NetworkPriority,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *Pod) GetIngress() uint64 {
	if x != nil {
		return x.Ingress
	}
	return 0
}

func (x *Pod) GetEgress() uint64 {
	if x != nil {
		return x.Egress
	}
	return 0
}

func (x *Pod) GetNetworkPriority() string {
	if x != nil {
		return x.NetworkPriority
	}
	return ""
}

type ReleaseIPRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	K8SPodName             string                 `protobuf:"bytes,1,opt,name=K8sPodName,proto3" json:"K8sPodName,omitempty"`
	K8SPodNamespace        string                 `protobuf:"bytes,2,opt,name=K8sPodNamespace,proto3" json:"K8sPodNamespace,omitempty"`
	K8SPodInfraContainerId string                 `protobuf:"bytes,3,opt,name=K8sPodInfraContainerId,proto3" json:"K8sPodInfraContainerId,omitempty"`
	IPType                 IPType                 `protobuf:"varint,4,opt,name=IPType,proto3,enum=rpc.IPType" json:"IPType,omitempty"`
	IPv4Addr               *IPSet                 `protobuf:"bytes,5,opt,name=IPv4Addr,proto3" json:"IPv4Addr,omitempty"`
	MacAddr                string                 `protobuf:"bytes,6,opt,name=MacAddr,proto3" json:"MacAddr,omitempty"`
	Reason                 string                 `protobuf:"bytes,7,opt,name=Reason,proto3" json:"Reason,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReleaseIPRequest) Reset() {
	*x = ReleaseIPRequest{}
	mi := &file_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPRequest) ProtoMessage() {}

func (x *ReleaseIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPRequest.ProtoReflect.Descriptor instead.
func (*ReleaseIPRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseIPRequest) GetK8SPodName() string {
	if x != nil {
		return x.K8SPodName
	}
	return ""
}

func (x *ReleaseIPRequest) GetK8SPodNamespace() string {
	if x != nil {
		return x.K8SPodNamespace
	}
	return ""
}

func (x *ReleaseIPRequest) GetK8SPodInfraContainerId() string {
	if x != nil {
		return x.K8SPodInfraContainerId
	}
	return ""
}

func (x *ReleaseIPRequest) GetIPType() IPType {
	if x != nil {
		return x.IPType
	}
	return IPType_TypeVPCIP
}

func (x *ReleaseIPRequest) GetIPv4Addr() *IPSet {
	if x != nil {
		return x.IPv4Addr
	}
	return nil
}

func (x *ReleaseIPRequest) GetMacAddr() string {
	if x != nil {
		return x.MacAddr
	}
	return ""
}

func (x *ReleaseIPRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseIPReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	IPv4Addr      *IPSet                 `protobuf:"bytes,2,opt,name=IPv4Addr,proto3" json:"IPv4Addr,omitempty"`
	DeviceNumber  int32                  `protobuf:"varint,3,opt,name=DeviceNumber,proto3" json:"DeviceNumber,omitempty"`
	IPv4          bool                   `protobuf:"varint,4,opt,name=IPv4,proto3" json:"IPv4,omitempty"`
	IPv6          bool                   `protobuf:"varint,5,opt,name=IPv6,proto3" json:"IPv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIPReply) Reset() {
	*x = ReleaseIPReply{}
	mi := &file_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPReply) ProtoMessage() {}

func (x *ReleaseIPReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPReply.ProtoReflect.Descriptor instead.
func (*ReleaseIPReply) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseIPReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseIPReply) GetIPv4Addr() *IPSet {
	if x != nil {
		return x.IPv4Addr
	}
	return nil
}

func (x *ReleaseIPReply) GetDeviceNumber() int32 {
	if x != nil {
		return x.DeviceNumber
	}
	return 0
}

func (x *ReleaseIPReply) GetIPv4() bool {
	if x != nil {
		return x.IPv4
	}
	return false
}

func (x *ReleaseIPReply) GetIPv6() bool {
	if x != nil {
		return x.IPv6
	}
	return false
}

type GetInfoRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	K8SPodName             string                 `protobuf:"bytes,1,opt,name=K8sPodName,proto3" json:"K8sPodName,omitempty"`
	K8SPodNamespace        string                 `protobuf:"bytes,2,opt,name=K8sPodNamespace,proto3" json:"K8sPodNamespace,omitempty"`
	K8SPodInfraContainerId string                 `protobuf:"bytes,3,opt,name=K8sPodInfraContainerId,proto3" json:"K8sPodInfraContainerId,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *GetInfoRequest) GetK8SPodName() string {
	if x != nil {
		return x.K8SPodName
	}
	return ""
}

func (x *GetInfoRequest) GetK8SPodNamespace() string {
	if x != nil {
		return x.K8SPodNamespace
	}
	return ""
}

func (x *GetInfoRequest) GetK8SPodInfraContainerId() string {
	if x != nil {
		return x.K8SPodInfraContainerId
	}
	return ""
}

type GetInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPType        IPType                 `protobuf:"varint,1,opt,name=IPType,proto3,enum=rpc.IPType" json:"IPType,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	IPv4          bool                   `protobuf:"varint,3,opt,name=IPv4,proto3" json:"IPv4,omitempty"`
	IPv6          bool                   `protobuf:"varint,4,opt,name=IPv6,proto3" json:"IPv6,omitempty"`
	NetConfs      []*NetConf             `protobuf:"bytes,5,rep,name=NetConfs,proto3" json:"NetConfs,omitempty"`
	Error         Error                  `protobuf:"varint,7,opt,name=Error,proto3,enum=rpc.Error" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoReply) Reset() {
	*x = GetInfoReply{}
	mi := &file_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoReply) ProtoMessage() {}

func (x *GetInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoReply.ProtoReflect.Descriptor instead.
func (*GetInfoReply) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *GetInfoReply) GetIPType() IPType {
	if x != nil {
		return x.IPType
	}
	return IPType_TypeVPCIP
}

func (x *GetInfoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetInfoReply) GetIPv4() bool {
	if x != nil {
		return x.IPv4
	}
	return false
}

func (x *GetInfoReply) GetIPv6() bool {
	if x != nil {
		return x.IPv6
	}
	return false
}

func (x *GetInfoReply) GetNetConfs() []*NetConf {
	if x != nil {
		return x.NetConfs
	}
	return nil
}

func (x *GetInfoReply) GetError() Error {
	if x != nil {
		return x.Error
	}
	return Error_ErrNoErr
}

type EventRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventTarget     EventTarget            `protobuf:"varint,1,opt,name=EventTarget,proto3,enum=rpc.EventTarget" json:"EventTarget,omitempty"`
	K8SPodName      string                 `protobuf:"bytes,2,opt,name=K8sPodName,proto3" json:"K8sPodName,omitempty"`
	K8SPodNamespace string                 `protobuf:"bytes,3,opt,name=K8sPodNamespace,proto3" json:"K8sPodNamespace,omitempty"`
	EventType       EventType              `protobuf:"varint,4,opt,name=EventType,proto3,enum=rpc.EventType" json:"EventType,omitempty"`
	Reason          string                 `protobuf:"bytes,5,opt,name=Reason,proto3" json:"Reason,omitempty"`
	Message         string                 `protobuf:"bytes,6,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *EventRequest) GetEventTarget() EventTarget {
	if x != nil {
		return x.EventTarget
	}
	return EventTarget_EventTargetNode
}

func (x *EventRequest) GetK8SPodName() string {
	if x != nil {
		return x.K8SPodName
	}
	return ""
}

func (x *EventRequest) GetK8SPodNamespace() string {
	if x != nil {
		return x.K8SPodNamespace
	}
	return ""
}

func (x *EventRequest) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EventTypeNormal
}

func (x *EventRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EventReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,1,opt,name=Succeed,proto3" json:"Succeed,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReply) Reset() {
	*x = EventReply{}
	mi := &file_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReply) ProtoMessage() {}

func (x *EventReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReply.ProtoReflect.Descriptor instead.
func (*EventReply) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *EventReply) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *EventReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x03rpc\"/\n" +
	"\x05IPSet\x12\x12\n" +
	"\x04IPv4\x18\x01 \x01(\tR\x04IPv4\x12\x12\n" +
	"\x04IPv6\x18\x02 \x01(\tR\x04IPv6\"\xc0\x01\n" +
	"\x0eAllocIPRequest\x12\x1e\n" +
	"\n" +
	"K8sPodName\x18\x01 \x01(\tR\n" +
	"K8sPodName\x12(\n" +
	"\x0fK8sPodNamespace\x18\x02 \x01(\tR\x0fK8sPodNamespace\x126\n" +
	"\x16K8sPodInfraContainerId\x18\x03 \x01(\tR\x16K8sPodInfraContainerId\x12\x14\n" +
	"\x05Netns\x18\x04 \x01(\tR\x05Netns\x12\x16\n" +
	"\x06IfName\x18\x05 \x01(\tR\x06IfName\"\xe5\x01\n" +
	"\aNetConf\x12,\n" +
	"\tBasicInfo\x18\x01 \x01(\v2\x0e.rpc.BasicInfoR\tBasicInfo\x12&\n" +
	"\aENIInfo\x18\x02 \x01(\v2\f.rpc.ENIInfoR\aENIInfo\x12\x1a\n" +
	"\x03Pod\x18\x03 \x01(\v2\b.rpc.PodR\x03Pod\x12\x16\n" +
	"\x06IfName\x18\x04 \x01(\tR\x06IfName\x12,\n" +
	"\vExtraRoutes\x18\x05 \x03(\v2\n" +
	".rpc.RouteR\vExtraRoutes\x12\"\n" +
	"\fDefaultRoute\x18\x06 \x01(\bR\fDefaultRoute\"\x9f\x01\n" +
	"\fAllocIPReply\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12#\n" +
	"\x06IPType\x18\x02 \x01(\x0e2\v.rpc.IPTypeR\x06IPType\x12\x12\n" +
	"\x04IPv4\x18\x03 \x01(\bR\x04IPv4\x12\x12\n" +
	"\x04IPv6\x18\x04 \x01(\bR\x04IPv6\x12(\n" +
	"\bNetConfs\x18\x05 \x03(\v2\f.rpc.NetConfR\bNetConfs\"\xab\x01\n" +
	"\tBasicInfo\x12 \n" +
	"\x05PodIP\x18\x01 \x01(\v2\n" +
	".rpc.IPSetR\x05PodIP\x12$\n" +
	"\aPodCIDR\x18\x02 \x01(\v2\n" +
	".rpc.IPSetR\aPodCIDR\x12(\n" +
	"\tGatewayIP\x18\x03 \x01(\v2\n" +
	".rpc.IPSetR\tGatewayIP\x12,\n" +
	"\vServiceCIDR\x18\x04 \x01(\v2\n" +
	".rpc.IPSetR\vServiceCIDR\"\xa5\x01\n" +
	"\aENIInfo\x12\x10\n" +
	"\x03MAC\x18\x01 \x01(\tR\x03MAC\x12\x14\n" +
	"\x05Trunk\x18\x02 \x01(\bR\x05Trunk\x12\x10\n" +
	"\x03Vid\x18\x03 \x01(\rR\x03Vid\x12(\n" +
	"\tGatewayIP\x18\x04 \x01(\v2\n" +
	".rpc.IPSetR\tGatewayIP\x12\x14\n" +
	"\x05eRDMA\x18\x05 \x01(\bR\x05eRDMA\x12\x17\n" +
	"\x04VfId\x18\x06 \x01(\rH\x00R\x04VfId\x88\x01\x01B\a\n" +
	"\x05_VfId\"\x19\n" +
	"\x05Route\x12\x10\n" +
	"\x03Dst\x18\x01 \x01(\tR\x03Dst\"a\n" +
	"\x03Pod\x12\x18\n" +
	"\aIngress\x18\x01 \x01(\x04R\aIngress\x12\x16\n" +
	"\x06Egress\x18\x02 \x01(\x04R\x06Egress\x12(\n" +
	"\x0fNetworkPriority\x18\x03 \x01(\tR\x0fNetworkPriority\"\x93\x02\n" +
	"\x10ReleaseIPRequest\x12\x1e\n" +
	"\n" +
	"K8sPodName\x18\x01 \x01(\tR\n" +
	"K8sPodName\x12(\n" +
	"\x0fK8sPodNamespace\x18\x02 \x01(\tR\x0fK8sPodNamespace\x126\n" +
	"\x16K8sPodInfraContainerId\x18\x03 \x01(\tR\x16K8sPodInfraContainerId\x12#\n" +
	"\x06IPType\x18\x04 \x01(\x0e2\v.rpc.IPTypeR\x06IPType\x12&\n" +
	"\bIPv4Addr\x18\x05 \x01(\v2\n" +
	".rpc.IPSetR\bIPv4Addr\x12\x18\n" +
	"\aMacAddr\x18\x06 \x01(\tR\aMacAddr\x12\x16\n" +
	"\x06Reason\x18\a \x01(\tR\x06Reason\"\x9e\x01\n" +
	"\x0eReleaseIPReply\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12&\n" +
	"\bIPv4Addr\x18\x02 \x01(\v2\n" +
	".rpc.IPSetR\bIPv4Addr\x12\"\n" +
	"\fDeviceNumber\x18\x03 \x01(\x05R\fDeviceNumber\x12\x12\n" +
	"\x04IPv4\x18\x04 \x01(\bR\x04IPv4\x12\x12\n" +
	"\x04IPv6\x18\x05 \x01(\bR\x04IPv6\"\x92\x01\n" +
	"\x0eGetInfoRequest\x12\x1e\n" +
	"\n" +
	"K8sPodName\x18\x01 \x01(\tR\n" +
	"K8sPodName\x12(\n" +
	"\x0fK8sPodNamespace\x18\x02 \x01(\tR\x0fK8sPodNamespace\x126\n" +
	"\x16K8sPodInfraContainerId\x18\x03 \x01(\tR\x16K8sPodInfraContainerId\"\xc1\x01\n" +
	"\fGetInfoReply\x12#\n" +
	"\x06IPType\x18\x01 \x01(\x0e2\v.rpc.IPTypeR\x06IPType\x12\x18\n" +
	"\aSuccess\x18\x02 \x01(\bR\aSuccess\x12\x12\n" +
	"\x04IPv4\x18\x03 \x01(\bR\x04IPv4\x12\x12\n" +
	"\x04IPv6\x18\x04 \x01(\bR\x04IPv6\x12(\n" +
	"\bNetConfs\x18\x05 \x03(\v2\f.rpc.NetConfR\bNetConfs\x12 \n" +
	"\x05Error\x18\a \x01(\x0e2\n" +
	".rpc.ErrorR\x05Error\"\xec\x01\n" +
	"\fEventRequest\x122\n" +
	"\vEventTarget\x18\x01 \x01(\x0e2\x10.rpc.EventTargetR\vEventTarget\x12\x1e\n" +
	"\n" +
	"K8sPodName\x18\x02 \x01(\tR\n" +
	"K8sPodName\x12(\n" +
	"\x0fK8sPodNamespace\x18\x03 \x01(\tR\x0fK8sPodNamespace\x12,\n" +
	"\tEventType\x18\x04 \x01(\x0e2\x0e.rpc.EventTypeR\tEventType\x12\x16\n" +
	"\x06Reason\x18\x05 \x01(\tR\x06Reason\x12\x18\n" +
	"\aMessage\x18\x06 \x01(\tR\aMessage\"<\n" +
	"\n" +
	"EventReply\x12\x18\n" +
	"\aSucceed\x18\x01 \x01(\bR\aSucceed\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error*;\n" +
	"\x06IPType\x12\r\n" +
	"\tTypeVPCIP\x10\x00\x12\x0e\n" +
	"\n" +
	"TypeVPCENI\x10\x01\x12\x12\n" +
	"\x0eTypeENIMultiIP\x10\x02*)\n" +
	"\x05Error\x12\f\n" +
	"\bErrNoErr\x10\x00\x12\x12\n" +
	"\x0eErrCRDNotFound\x10\x01*6\n" +
	"\vEventTarget\x12\x13\n" +
	"\x0fEventTargetNode\x10\x00\x12\x12\n" +
	"\x0eEventTargetPod\x10\x01*6\n" +
	"\tEventType\x12\x13\n" +
	"\x0fEventTypeNormal\x10\x00\x12\x14\n" +
	"\x10EventTypeWarning\x10\x012\xeb\x01\n" +
	"\rTerwayBackend\x123\n" +
	"\aAllocIP\x12\x13.rpc.AllocIPRequest\x1a\x11.rpc.AllocIPReply\"\x00\x129\n" +
	"\tReleaseIP\x12\x15.rpc.ReleaseIPRequest\x1a\x13.rpc.ReleaseIPReply\"\x00\x125\n" +
	"\tGetIPInfo\x12\x13.rpc.GetInfoRequest\x1a\x11.rpc.GetInfoReply\"\x00\x123\n" +
	"\vRecordEvent\x12\x11.rpc.EventRequest\x1a\x0f.rpc.EventReply\"\x00B\bZ\x06./;rpcb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rpc_proto_goTypes = []any{
	(IPType)(0),              // 0: rpc.IPType
	(Error)(0),               // 1: rpc.Error
	(EventTarget)(0),         // 2: rpc.EventTarget
	(EventType)(0),           // 3: rpc.EventType
	(*IPSet)(nil),            // 4: rpc.IPSet
	(*AllocIPRequest)(nil),   // 5: rpc.AllocIPRequest
	(*NetConf)(nil),          // 6: rpc.NetConf
	(*AllocIPReply)(nil),     // 7: rpc.AllocIPReply
	(*BasicInfo)(nil),        // 8: rpc.BasicInfo
	(*ENIInfo)(nil),          // 9: rpc.ENIInfo
	(*Route)(nil),            // 10: rpc.Route
	(*Pod)(nil),              // 11: rpc.Pod
	(*ReleaseIPRequest)(nil), // 12: rpc.ReleaseIPRequest
	(*ReleaseIPReply)(nil),   // 13: rpc.ReleaseIPReply
	(*GetInfoRequest)(nil),   // 14: rpc.GetInfoRequest
	(*GetInfoReply)(nil),     // 15: rpc.GetInfoReply
	(*EventRequest)(nil),     // 16: rpc.EventRequest
	(*EventReply)(nil),       // 17: rpc.EventReply
}
var file_rpc_proto_depIdxs = []int32{
	8,  // 0: rpc.NetConf.BasicInfo:type_name -> rpc.BasicInfo
	9,  // 1: rpc.NetConf.ENIInfo:type_name -> rpc.ENIInfo
	11, // 2: rpc.NetConf.Pod:type_name -> rpc.Pod
	10, // 3: rpc.NetConf.ExtraRoutes:type_name -> rpc.Route
	0,  // 4: rpc.AllocIPReply.IPType:type_name -> rpc.IPType
	6,  // 5: rpc.AllocIPReply.NetConfs:type_name -> rpc.NetConf
	4,  // 6: rpc.BasicInfo.PodIP:type_name -> rpc.IPSet
	4,  // 7: rpc.BasicInfo.PodCIDR:type_name -> rpc.IPSet
	4,  // 8: rpc.BasicInfo.GatewayIP:type_name -> rpc.IPSet
	4,  // 9: rpc.BasicInfo.ServiceCIDR:type_name -> rpc.IPSet
	4,  // 10: rpc.ENIInfo.GatewayIP:type_name -> rpc.IPSet
	0,  // 11: rpc.ReleaseIPRequest.IPType:type_name -> rpc.IPType
	4,  // 12: rpc.ReleaseIPRequest.IPv4Addr:type_name -> rpc.IPSet
	4,  // 13: rpc.ReleaseIPReply.IPv4Addr:type_name -> rpc.IPSet
	0,  // 14: rpc.GetInfoReply.IPType:type_name -> rpc.IPType
	6,  // 15: rpc.GetInfoReply.NetConfs:type_name -> rpc.NetConf
	1,  // 16: rpc.GetInfoReply.Error:type_name -> rpc.Error
	2,  // 17: rpc.EventRequest.EventTarget:type_name -> rpc.EventTarget
	3,  // 18: rpc.EventRequest.EventType:type_name -> rpc.EventType
	5,  // 19: rpc.TerwayBackend.AllocIP:input_type -> rpc.AllocIPRequest
	12, // 20: rpc.TerwayBackend.ReleaseIP:input_type -> rpc.ReleaseIPRequest
	14, // 21: rpc.TerwayBackend.GetIPInfo:input_type -> rpc.GetInfoRequest
	16, // 22: rpc.TerwayBackend.RecordEvent:input_type -> rpc.EventRequest
	7,  // 23: rpc.TerwayBackend.AllocIP:output_type -> rpc.AllocIPReply
	13, // 24: rpc.TerwayBackend.ReleaseIP:output_type -> rpc.ReleaseIPReply
	15, // 25: rpc.TerwayBackend.GetIPInfo:output_type -> rpc.GetInfoReply
	17, // 26: rpc.TerwayBackend.RecordEvent:output_type -> rpc.EventReply
	23, // [23:27] is the sub-list for method output_type
	19, // [19:23] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_rpc_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		EnumInfos:         file_rpc_proto_enumTypes,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
