// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: tracing.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Placeholder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Placeholder) Reset() {
	*x = Placeholder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Placeholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placeholder) ProtoMessage() {}

func (x *Placeholder) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placeholder.ProtoReflect.Descriptor instead.
func (*Placeholder) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{0}
}

type ResourcesTypesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeNames []string `protobuf:"bytes,1,rep,name=TypeNames,proto3" json:"TypeNames,omitempty"`
}

func (x *ResourcesTypesReply) Reset() {
	*x = ResourcesTypesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourcesTypesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesTypesReply) ProtoMessage() {}

func (x *ResourcesTypesReply) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesTypesReply.ProtoReflect.Descriptor instead.
func (*ResourcesTypesReply) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{1}
}

func (x *ResourcesTypesReply) GetTypeNames() []string {
	if x != nil {
		return x.TypeNames
	}
	return nil
}

type ResourcesNamesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceNames []string `protobuf:"bytes,1,rep,name=ResourceNames,proto3" json:"ResourceNames,omitempty"`
}

func (x *ResourcesNamesReply) Reset() {
	*x = ResourcesNamesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourcesNamesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesNamesReply) ProtoMessage() {}

func (x *ResourcesNamesReply) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesNamesReply.ProtoReflect.Descriptor instead.
func (*ResourcesNamesReply) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{2}
}

func (x *ResourcesNamesReply) GetResourceNames() []string {
	if x != nil {
		return x.ResourceNames
	}
	return nil
}

type ResourceTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ResourceTypeRequest) Reset() {
	*x = ResourceTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTypeRequest) ProtoMessage() {}

func (x *ResourceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTypeRequest.ProtoReflect.Descriptor instead.
func (*ResourceTypeRequest) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResourceTypeNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ResourceTypeNameRequest) Reset() {
	*x = ResourceTypeNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceTypeNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTypeNameRequest) ProtoMessage() {}

func (x *ResourceTypeNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTypeNameRequest.ProtoReflect.Descriptor instead.
func (*ResourceTypeNameRequest) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceTypeNameRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceTypeNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResourceExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Command string   `protobuf:"bytes,3,opt,name=Command,proto3" json:"Command,omitempty"`
	Args    []string `protobuf:"bytes,4,rep,name=Args,proto3" json:"Args,omitempty"`
}

func (x *ResourceExecuteRequest) Reset() {
	*x = ResourceExecuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceExecuteRequest) ProtoMessage() {}

func (x *ResourceExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceExecuteRequest.ProtoReflect.Descriptor instead.
func (*ResourceExecuteRequest) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceExecuteRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceExecuteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ResourceExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ResourceExecuteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *ResourceExecuteReply) Reset() {
	*x = ResourceExecuteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceExecuteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceExecuteReply) ProtoMessage() {}

func (x *ResourceExecuteReply) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceExecuteReply.ProtoReflect.Descriptor instead.
func (*ResourceExecuteReply) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceExecuteReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MapKeyValueEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MapKeyValueEntry) Reset() {
	*x = MapKeyValueEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapKeyValueEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapKeyValueEntry) ProtoMessage() {}

func (x *MapKeyValueEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapKeyValueEntry.ProtoReflect.Descriptor instead.
func (*MapKeyValueEntry) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{7}
}

func (x *MapKeyValueEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapKeyValueEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ResourceConfigReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config []*MapKeyValueEntry `protobuf:"bytes,1,rep,name=Config,proto3" json:"Config,omitempty"`
}

func (x *ResourceConfigReply) Reset() {
	*x = ResourceConfigReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfigReply) ProtoMessage() {}

func (x *ResourceConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfigReply.ProtoReflect.Descriptor instead.
func (*ResourceConfigReply) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceConfigReply) GetConfig() []*MapKeyValueEntry {
	if x != nil {
		return x.Config
	}
	return nil
}

type ResourceTraceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trace []*MapKeyValueEntry `protobuf:"bytes,1,rep,name=Trace,proto3" json:"Trace,omitempty"`
}

func (x *ResourceTraceReply) Reset() {
	*x = ResourceTraceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceTraceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTraceReply) ProtoMessage() {}

func (x *ResourceTraceReply) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTraceReply.ProtoReflect.Descriptor instead.
func (*ResourceTraceReply) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceTraceReply) GetTrace() []*MapKeyValueEntry {
	if x != nil {
		return x.Trace
	}
	return nil
}

type ResourceMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkInterfaceID   string   `protobuf:"bytes,1,opt,name=NetworkInterfaceID,proto3" json:"NetworkInterfaceID,omitempty"`
	MAC                  string   `protobuf:"bytes,2,opt,name=MAC,proto3" json:"MAC,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	AllocInhibitExpireAt string   `protobuf:"bytes,4,opt,name=AllocInhibitExpireAt,proto3" json:"AllocInhibitExpireAt,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Info                 []string `protobuf:"bytes,6,rep,name=Info,proto3" json:"Info,omitempty"`
}

func (x *ResourceMapping) Reset() {
	*x = ResourceMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMapping) ProtoMessage() {}

func (x *ResourceMapping) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMapping.ProtoReflect.Descriptor instead.
func (*ResourceMapping) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{10}
}

func (x *ResourceMapping) GetNetworkInterfaceID() string {
	if x != nil {
		return x.NetworkInterfaceID
	}
	return ""
}

func (x *ResourceMapping) GetMAC() string {
	if x != nil {
		return x.MAC
	}
	return ""
}

func (x *ResourceMapping) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceMapping) GetAllocInhibitExpireAt() string {
	if x != nil {
		return x.AllocInhibitExpireAt
	}
	return ""
}

func (x *ResourceMapping) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResourceMapping) GetInfo() []string {
	if x != nil {
		return x.Info
	}
	return nil
}

type ResourceMappingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info []*ResourceMapping `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
}

func (x *ResourceMappingReply) Reset() {
	*x = ResourceMappingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracing_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceMappingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMappingReply) ProtoMessage() {}

func (x *ResourceMappingReply) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMappingReply.ProtoReflect.Descriptor instead.
func (*ResourceMappingReply) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceMappingReply) GetInfo() []*ResourceMapping {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_tracing_proto protoreflect.FileDescriptor

var file_tracing_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x72, 0x70, 0x63, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c,
	0x64, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x79,
	0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x54,
	0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x24, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x41, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x6e, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x41,
	0x72, 0x67, 0x73, 0x22, 0x30, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x44, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d,
	0x61, 0x70, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x41, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a,
	0x05, 0x54, 0x72, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x54, 0x72, 0x61, 0x63, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x2e,
	0x0a, 0x12, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x41, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x41, 0x43,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x49, 0x6e, 0x68,
	0x69, 0x62, 0x69, 0x74, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x14, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x49, 0x6e, 0x68, 0x69, 0x62, 0x69, 0x74,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x40, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x32, 0xbb, 0x03, 0x0a, 0x0d, 0x54, 0x65, 0x72, 0x77, 0x61,
	0x79, 0x54, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x3e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x10, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x1a, 0x18,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4b, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x1c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x1c, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x4b, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x30,
	0x01, 0x12, 0x41, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x1a, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tracing_proto_rawDescOnce sync.Once
	file_tracing_proto_rawDescData = file_tracing_proto_rawDesc
)

func file_tracing_proto_rawDescGZIP() []byte {
	file_tracing_proto_rawDescOnce.Do(func() {
		file_tracing_proto_rawDescData = protoimpl.X.CompressGZIP(file_tracing_proto_rawDescData)
	})
	return file_tracing_proto_rawDescData
}

var file_tracing_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tracing_proto_goTypes = []interface{}{
	(*Placeholder)(nil),             // 0: rpc.Placeholder
	(*ResourcesTypesReply)(nil),     // 1: rpc.ResourcesTypesReply
	(*ResourcesNamesReply)(nil),     // 2: rpc.ResourcesNamesReply
	(*ResourceTypeRequest)(nil),     // 3: rpc.ResourceTypeRequest
	(*ResourceTypeNameRequest)(nil), // 4: rpc.ResourceTypeNameRequest
	(*ResourceExecuteRequest)(nil),  // 5: rpc.ResourceExecuteRequest
	(*ResourceExecuteReply)(nil),    // 6: rpc.ResourceExecuteReply
	(*MapKeyValueEntry)(nil),        // 7: rpc.MapKeyValueEntry
	(*ResourceConfigReply)(nil),     // 8: rpc.ResourceConfigReply
	(*ResourceTraceReply)(nil),      // 9: rpc.ResourceTraceReply
	(*ResourceMapping)(nil),         // 10: rpc.ResourceMapping
	(*ResourceMappingReply)(nil),    // 11: rpc.ResourceMappingReply
}
var file_tracing_proto_depIdxs = []int32{
	7,  // 0: rpc.ResourceConfigReply.Config:type_name -> rpc.MapKeyValueEntry
	7,  // 1: rpc.ResourceTraceReply.Trace:type_name -> rpc.MapKeyValueEntry
	10, // 2: rpc.ResourceMappingReply.info:type_name -> rpc.ResourceMapping
	0,  // 3: rpc.TerwayTracing.GetResourceTypes:input_type -> rpc.Placeholder
	3,  // 4: rpc.TerwayTracing.GetResources:input_type -> rpc.ResourceTypeRequest
	4,  // 5: rpc.TerwayTracing.GetResourceConfig:input_type -> rpc.ResourceTypeNameRequest
	4,  // 6: rpc.TerwayTracing.GetResourceTrace:input_type -> rpc.ResourceTypeNameRequest
	5,  // 7: rpc.TerwayTracing.ResourceExecute:input_type -> rpc.ResourceExecuteRequest
	0,  // 8: rpc.TerwayTracing.GetResourceMapping:input_type -> rpc.Placeholder
	1,  // 9: rpc.TerwayTracing.GetResourceTypes:output_type -> rpc.ResourcesTypesReply
	2,  // 10: rpc.TerwayTracing.GetResources:output_type -> rpc.ResourcesNamesReply
	8,  // 11: rpc.TerwayTracing.GetResourceConfig:output_type -> rpc.ResourceConfigReply
	9,  // 12: rpc.TerwayTracing.GetResourceTrace:output_type -> rpc.ResourceTraceReply
	6,  // 13: rpc.TerwayTracing.ResourceExecute:output_type -> rpc.ResourceExecuteReply
	11, // 14: rpc.TerwayTracing.GetResourceMapping:output_type -> rpc.ResourceMappingReply
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_tracing_proto_init() }
func file_tracing_proto_init() {
	if File_tracing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tracing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Placeholder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourcesTypesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourcesNamesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceTypeNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceExecuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceExecuteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapKeyValueEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfigReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceTraceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracing_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceMappingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tracing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracing_proto_goTypes,
		DependencyIndexes: file_tracing_proto_depIdxs,
		MessageInfos:      file_tracing_proto_msgTypes,
	}.Build()
	File_tracing_proto = out.File
	file_tracing_proto_rawDesc = nil
	file_tracing_proto_goTypes = nil
	file_tracing_proto_depIdxs = nil
}
