apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terway-controlplane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: terway-controlplane
subjects:
  - kind: ServiceAccount
    name: terway-controlplane
    namespace: {{ .Release.Namespace }}