apiVersion: v1
kind: Service
metadata:
  name: terway-controlplane
  labels:
    {{- include "terway-controlplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.terwayControlplane.service.type }}
  ports:
    - port: {{ .Values.terwayControlplane.service.port }}
      targetPort: 4443
      protocol: TCP
      name: https
  selector:
    {{- include "terway-controlplane.selectorLabels" . | nindent 4 }}
