# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
    - image: circleci/golang:1.15
    working_directory: /go/src/github.com/AliyunContainerService/terway
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: codecov
        command: |
          go test -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)

  code-check:
    docker:
      - image: l1b0k/terway-golangci-lint:v1.0.0
    working_directory: /go/src/github.com/AliyunContainerService/terway
    steps:
      - checkout
      - run:
          name: use markdown-link-check(https://github.com/tcort/markdown-link-check) to check links in markdown files
          command: |
            set +e
            for name in $(find . -name \*.md | grep -v vendor); do
              if [ -f $name ]; then
                markdown-link-check -q $name;
                if [ $? -ne 0 ]; then
                  code=1
                fi
              fi
            done
            bash -c "exit $code";

  markdown-spellcheck:
    docker:
        - image: sunyuan3/markdown-spellcheck:v1
    working_directory: /go/src/github.com/AliyunContainerService/terway
    steps:
      - checkout
      - run:
          name: markdown spellcheck
          command: |
            find . -name \*.md | grep -v '^./vendor' | grep  -v ./README-zh_C | xargs mdspell --ignore-numbers --ignore-acronyms --en-us -r -x

workflows:
  ci:
    jobs:
      - build
      - code-check
      - markdown-spellcheck
