# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/AliyunContainerService/terway
    steps:
    - checkout
    - setup_remote_docker:
          docker_layer_caching: true
    - run:
        name: run tests
        command: |
          test -z $(go fmt ./...)
          go vet ./...
          go test -race -v ./...
    - run: docker build -t acs/terway:$CIRCLE_BUILD_NUM .
    - run:
        name: codecov
        command: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)

  code-check:
    docker:
      - image: pouchcontainer/pouchlinter:v0.1.2
    working_directory: /go/src/github.com/AliyunContainerService/terway
    steps:
      - checkout
      - run:
          name: validate go code with gometalinter
          command: |
            gometalinter --disable-all --skip vendor -E gofmt -E ineffassign -E misspell -E vet -d ./...
      - run:
          name: use opensource tool client9/misspell to correct commonly misspelled English words 
          command: |
            find  ./* -name  "*"  | grep -v vendor | xargs misspell -error

  markdown-spellcheck:
    docker:
        - image: registry.cn-shanghai.aliyuncs.com/sunyuan/markdown-spellcheck:v1
    working_directory: /go/src/github.com/AliyunContainerService/terway
    steps:
      - checkout
      - run:
          name: markdown spellcheck
          command: |
            find . -name \*.md | grep -v '^./vendor' | grep  -v ./README-zh_C | xargs mdspell --ignore-numbers --ignore-acronyms --en-us -r -x

workflows:
  version: 2
  ci:
    jobs:
      - build
      - code-check
      - markdown-spellcheck
