{
 "title": "Terway Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Terway Resource Pool Total Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "terway_resource_pool_total_count",
     "legendFormat": "{{instance}}({{capacity}})"
    }
   ]
  },
  {
   "title": "Terway Resource Pool Idle Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "terway_resource_pool_idle_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Terway Resource Pool Total Count Time Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "terway_resource_pool_total_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Terway Resource Pool Idle Count Time Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "terway_resource_pool_idle_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Aliyun Metadata API Latency 95%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aliyun_metadata_latency_bucket[5m])) by (le, url))"
    }
   ]
  },
  {
   "title": "Aliyun OpenAPI Latency 95%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aliyun_openapi_latency_bucket[5m])) by (le, api))"
    }
   ]
  },
  {
   "title": "Aliyun Metadata Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_metadata_latency_count) by (error)"
    }
   ]
  },
  {
   "title": "Aliyun OpenAPI Reqeust Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_openapi_latency_count) by (error)"
    }
   ]
  },
  {
   "title": "Terway Resource Pool Disposed Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "terway_resource_pool_disposed_count",
     "legendFormat": "{{instance}}({{min_idle}}-{{max_idle}})"
    }
   ]
  },
  {
   "title": "Terway ENIIP Factory ENI Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "terway_eniip_factory_eni_count", "legendFormat": "{{instance}}({{max_eni}})" }
   ]
  },
  {
   "title": "Terway ENIIP Factory IP Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    { "expr": "terway_eniip_factory_ip_count", "legendFormat": "{{eni}}({{instance}})" }
   ]
  },
  {
   "title": "Terway ENIIP Factory IP Alloc Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(terway_eniip_factory_ip_alloc_count) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}