kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terway-pod-reader
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - nodes
      - namespaces
{{- if (not .Values.terway.enableDatapathV2) }}
      - serviceaccounts
{{- end }}
      - endpoints
      - services
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ''
    resources:
      - pods
      - nodes
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - crd.projectcalico.org
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cilium.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - network.alibabacloud.com
    resources:
      - podenis
      - nodes
      - noderuntimes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - network.alibabacloud.com
    resources:
      - nodes
    verbs:
      - patch
      - update
  - apiGroups:
      - network.alibabacloud.com
    resources:
      - noderuntimes
      - noderuntimes/status
    verbs:
      - create
      - patch
      - update