---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: terway-eniip
spec:
  selector:
    matchLabels:
      app: terway-eniip
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: terway-eniip
      annotations:
        # As of Kubernetes v1.30, this should be set with the appArmorProfile field instead.
        container.apparmor.security.beta.kubernetes.io/policy: unconfined
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      tolerations:
        - operator: "Exists"
      terminationGracePeriodSeconds: 0
      serviceAccountName: terway
      hostNetwork: true
      initContainers:
        - name: terway-init
          image: "{{ .Values.terway.image.repository }}:{{ .Values.terway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /usr/bin/init.sh
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DISABLE_POLICY
              valueFrom:
                configMapKeyRef:
                  name: eni-config
                  key: disable_network_policy
                  optional: true
          volumeMounts:
            - name: bpf-maps
              mountPath: /sys/fs/bpf
              mountPropagation: Bidirectional
            - name: eni-config
              mountPath: /etc/eni
            - mountPath: /var-run-eni
              name: var-run-eni
            - name: cni-bin
              mountPath: /opt/cni/bin/
            - name: cni
              mountPath: /etc/cni/net.d/
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /host
              name: host-root
            - mountPath: /var/run/
              name: eni-run
      containers:
        - name: terway
          image: "{{ .Values.terway.image.repository }}:{{ .Values.terway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command:
            - "/usr/bin/terwayd"
            - "-log-level"
            - "info"
            - "-daemon-mode"
            - "{{.Values.terway.daemonMode}}"
            - "-config"
            - "/etc/eni/eni_conf"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - DAC_OVERRIDE
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 256Mi
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: eni-config
              mountPath: /etc/eni
              readOnly: true
            - mountPath: /var/run/
              name: eni-run
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /var/lib/cni/terway
              name: cni-terway
            - mountPath: /etc/cni/net.d
              name: cni
              readOnly: true
            - mountPath: /host-etc-net.d
              name: host-cni
            - mountPath: /var/lib/kubelet/device-plugins
              name: device-plugin-path
            - mountPath: /etc/eflo_config
              name: eflo
              readOnly: true
        - name: policy
          image: "{{ .Values.terway.image.repository }}:{{ .Values.terway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command: [ "/usr/bin/policyinit.sh" ]
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DISABLE_POLICY
              valueFrom:
                configMapKeyRef:
                  name: eni-config
                  key: disable_network_policy
                  optional: true
            - name: FELIX_TYPHAK8SSERVICENAME
              valueFrom:
                configMapKeyRef:
                  name: eni-config
                  key: felix_relay_service
                  optional: true
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CILIUM_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CILIUM_CNI_CHAINING_MODE
              value: terway-chainer
          securityContext:
{{- if .Values.appArmorProfile }}
            appArmorProfile:
{{ toYaml .Values.appArmorProfile | trim | indent 14 }}
{{- end }}
            seccompProfile:
              type: Unconfined
            privileged: false
            capabilities:
              add:
                - NET_ADMIN
                - DAC_OVERRIDE
                - SYS_ADMIN
                - NET_RAW
                - SYS_MODULE
{{- if or .Values.terway.enableDatapathV2 (eq .Values.terway.networkPolicyProvider "ebpf") }}
                - CHOWN
                - IPC_LOCK
                - SYS_RESOURCE
{{- end }}
          resources:
            requests:
              cpu: 250m
              memory: 100Mi
            limits:
              cpu: "1"
          livenessProbe:
            tcpSocket:
              port: 9099
              host: 127.0.0.1
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 9099
              host: 127.0.0.1
            periodSeconds: 10
          volumeMounts:
            - name: eni-config
              mountPath: /etc/eni
              readOnly: true
            - mountPath: /var-run-eni
              name: var-run-eni
              readOnly: true
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /etc/cni/net.d
              name: cni
              readOnly: true
            # volumes use by cilium
            - name: bpf-maps
              mountPath: /sys/fs/bpf
              # Unprivileged containers can't set mount propagation to bidirectional
              # in this case we will mount the bpf fs from an init container that
              # is privileged and set the mount propagation from host to container
              # in Cilium.
              mountPropagation: HostToContainer
            - mountPath: /var/run/cilium
              name: cilium-run
              # Needed to be able to load kernel modules
            - mountPath: /run/xtables.lock
              name: xtables-lock
      volumes:
        - name: var-run-eni
          emptyDir: { }
        - name: eni-config
          configMap:
            name: eni-config
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
            type: "Directory"
        - name: host-cni
          hostPath:
            path: /etc/cni/net.d
        - name: cni
          emptyDir: { }
        - name: eni-run
          hostPath:
            path: /var/run/
            type: "Directory"
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: cni-terway
          hostPath:
            path: /var/lib/cni/terway
        - name: device-plugin-path
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: "Directory"
        - name: host-root
          hostPath:
            path: /
            type: "Directory"
        # used by cilium
        # To keep state between restarts / upgrades
        - hostPath:
            path: /var/run/cilium
            type: DirectoryOrCreate
          name: cilium-run
        # To keep state between restarts / upgrades for bpf maps
        - name: bpf-maps
          hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
          # To access iptables concurrently with other processes (e.g. kube-proxy)
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
        - hostPath:
            path: /etc/eflo_config
            type: DirectoryOrCreate
          name: eflo
---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: felixconfigurations.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
  names:
    kind: FelixConfiguration
    plural: felixconfigurations
    singular: felixconfiguration

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bgpconfigurations.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
  names:
    kind: BGPConfiguration
    plural: bgpconfigurations
    singular: bgpconfiguration

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ippools.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
  names:
    kind: IPPool
    plural: ippools
    singular: ippool

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hostendpoints.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
  names:
    kind: HostEndpoint
    plural: hostendpoints
    singular: hostendpoint

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterinformations.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
  names:
    kind: ClusterInformation
    plural: clusterinformations
    singular: clusterinformation

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globalnetworkpolicies.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
  names:
    kind: GlobalNetworkPolicy
    plural: globalnetworkpolicies
    singular: globalnetworkpolicy

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globalnetworksets.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
  names:
    kind: GlobalNetworkSet
    plural: globalnetworksets
    singular: globalnetworkset

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkpolicies.crd.projectcalico.org
spec:
  scope: Namespaced
  group: crd.projectcalico.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
  names:
    kind: NetworkPolicy
    plural: networkpolicies
    singular: networkpolicy
