apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terway-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: terway
subjects:
  - kind: ServiceAccount
    name: terway
    namespace: {{ .Release.Namespace }}