# Default values for terway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry-cn-hangzhou.ack.aliyuncs.com/acs/terway
  pullPolicy: IfNotPresent
  tag: "v1.6.0"

nameOverride: ""
fullnameOverride: ""

# daemonMode: options [ ENIMultiIP, ENIOnly, VPC ]
daemonMode: ENIMultiIP
enableIPvlan: false

# ipStack: options [ ipv4, ipv6, dual ]
ipStack: ipv4

securityGroupIDs:
  - sg-1
vSwitchIDs:
  cn-hangzhou-k:
    - vsw-1

serviceCIDR: "10.96.0.0/12"

# secrets
accessKey: ""
accessSecret: ""