apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}
rules:
  - apiGroups: [ "" ]
    resources:
      - secrets
    verbs:
      - create
  - apiGroups: [ "" ]
    resources:
      - secrets
    verbs:
      - get
      - update
      - patch
      - watch
    resourceNames:
      - {{ .Chart.Name }}
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update