apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credential
  labels:
  {{- include "terway-controlplane.labels" . | nindent 4 }}
stringData:
  ctrl-secret.yaml: |
    accessKey: "{{ .Values.accessKey }}"
    accessSecret: "{{ .Values.accessSecret }}"
    otelEndpoint: "{{ .Values.otelEndpoint }}"
    otelToken: "{{ .Values.otelToken }}"
    secretNamespace: "{{ .Values.secretNamespace }}"
    secretName: "{{ .Values.secretName }}"
