apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "terway-controlplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
      protocol: TCP
      name: http
  selector:
    {{- include "terway-controlplane.selectorLabels" . | nindent 4 }}
