apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "terway-controlplane.labels" . | nindent 4 }}
webhooks:
  - name: {{ .Chart.Name }}.mutating.k8s.io
    namespaceSelector:
      matchExpressions:
        - key: k8s.aliyun.com/pod-eni
          operator: NotIn
          values: ["false"]
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
        scope:       "Namespaced"
      - apiGroups:   ["network.alibabacloud.com"]
        apiVersions: ["*"]
        operations:  ["CREATE"]
        resources:   ["podnetworkings"]
        scope:       "Cluster"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: /mutating
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: {{ .Values.webhookTimeoutSeconds }}
    failurePolicy: {{ .Values.webhookFailurePolicy }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "terway-controlplane.labels" . | nindent 4 }}
webhooks:
  - name: {{ .Chart.Name }}.validate.k8s.io
    rules:
      - apiGroups:   ["network.alibabacloud.com"]
        apiVersions: ["*"]
        operations:  ["CREATE"]
        resources:   ["podnetworkings"]
        scope:       "Cluster"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: /validate
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: {{ .Values.webhookTimeoutSeconds }}
    failurePolicy: Fail