#!/bin/sh
export DATASTORE_TYPE=kubernetes
export FELIX_LOGSEVERITYSYS=info
export CALICO_NETWORKING_BACKEND=none
export CLUSTER_TYPE=k8s,canal
export CALICO_DISABLE_FILE_LOGGING=true
export CALICO_IPV4POOL_CIDR=${Network:-'10.244.0.0/16'}
export FELIX_IPTABLESREFRESHINTERVAL=${IPTABLESREFRESHINTERVAL:-60}
export FELIX_IPV6SUPPORT=false
export WAIT_FOR_DATASTORE=true
export IP=""
export FELIX_DEFAULTENDPOINTTOHOSTACTION=ACCEPT
export FELIX_HEALTHENABLED=true
exec 2>&1
if [ ! -z $NODENAME ]; then
    export FELIX_FELIXHOSTNAME=$NODENAME
fi
if [ ! -z $DATASTORE_TYPE ]; then
    export FELIX_DATASTORETYPE=$DATASTORE_TYPE
fi
exec calico-felix
