---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terway-pod-reader
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - nodes
      - namespaces
      - configmaps
      - serviceaccounts
      - endpoints
      - services
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ''
    resources:
      - pods
      - nodes
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - watch
      - update
      - create
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods/status
    verbs:
      - update
  - apiGroups:
      - crd.projectcalico.org
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - cilium.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - network.alibabacloud.com
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - alibabacloud.com
    resources:
      - '*'
    verbs:
      - '*'