# Default values for terway-controlplane.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: l1b0k/terway-controlplane
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 443

resources:
   requests:
     cpu: 100m
     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

webhookFailurePolicy: Ignore
webhookTimeoutSeconds: 10

# configmap
regionID: ch-hangzhou
clusterID: ""
vpcID: ""

ipStack: ipv4

# secrets
accessKey: ""
accessSecret: ""
