{{- if .Values.terwayMigrate.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "terway.migrate.serviceAccountName" . }}
  labels:
    {{- include "terway.labels" . | nindent 4 }}
    app.kubernetes.io/component: terway-migrate
automountServiceAccountToken: true
{{- end }}
