name: build

on:
  push:
    branches: [main]
    tags:
    - 'v*'
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  build-terway:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:qemu-v7.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [[worker.oci.gcpolicy]]
          minFreeSpace = "1GB"
          [[worker.oci.gcpolicy]]
          all = true
          minFreeSpace = "1GB"

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event_name != 'pull_request' && github.event.action != 'unassigned' }}

    - uses: crazy-max/ghaction-github-runtime@v3
    - name: Build
      run: |
        make REGISTRY=ghcr.io/aliyuncontainerservice PUSH=$PUSH build
      env:
        PUSH: ${{ github.event_name != 'pull_request' && github.event.action != 'unassigned' }}
