// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/AliyunContainerService/terway/pkg/aliyun/client"

	ecs "github.com/aliyun/alibaba-cloud-sdk-go/services/ecs"

	mock "github.com/stretchr/testify/mock"

	netip "net/netip"

	vpc "github.com/aliyun/alibaba-cloud-sdk-go/services/vpc"

	wait "k8s.io/apimachinery/pkg/util/wait"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// AssignIpv6Addresses provides a mock function with given fields: ctx, opts
func (_m *Interface) AssignIpv6Addresses(ctx context.Context, opts ...client.AssignIPv6AddressesOption) ([]netip.Addr, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AssignIpv6Addresses")
	}

	var r0 []netip.Addr
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.AssignIPv6AddressesOption) ([]netip.Addr, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...client.AssignIPv6AddressesOption) []netip.Addr); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]netip.Addr)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...client.AssignIPv6AddressesOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AssignPrivateIPAddress provides a mock function with given fields: ctx, opts
func (_m *Interface) AssignPrivateIPAddress(ctx context.Context, opts ...client.AssignPrivateIPAddressOption) ([]netip.Addr, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AssignPrivateIPAddress")
	}

	var r0 []netip.Addr
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.AssignPrivateIPAddressOption) ([]netip.Addr, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...client.AssignPrivateIPAddressOption) []netip.Addr); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]netip.Addr)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...client.AssignPrivateIPAddressOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AttachNetworkInterface provides a mock function with given fields: ctx, eniID, instanceID, trunkENIID
func (_m *Interface) AttachNetworkInterface(ctx context.Context, eniID string, instanceID string, trunkENIID string) error {
	ret := _m.Called(ctx, eniID, instanceID, trunkENIID)

	if len(ret) == 0 {
		panic("no return value specified for AttachNetworkInterface")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, eniID, instanceID, trunkENIID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateNetworkInterface provides a mock function with given fields: ctx, opts
func (_m *Interface) CreateNetworkInterface(ctx context.Context, opts ...client.CreateNetworkInterfaceOption) (*client.NetworkInterface, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateNetworkInterface")
	}

	var r0 *client.NetworkInterface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.CreateNetworkInterfaceOption) (*client.NetworkInterface, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...client.CreateNetworkInterfaceOption) *client.NetworkInterface); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.NetworkInterface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...client.CreateNetworkInterfaceOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNetworkInterface provides a mock function with given fields: ctx, eniID
func (_m *Interface) DeleteNetworkInterface(ctx context.Context, eniID string) error {
	ret := _m.Called(ctx, eniID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNetworkInterface")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, eniID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DescribeInstanceTypes provides a mock function with given fields: ctx, types
func (_m *Interface) DescribeInstanceTypes(ctx context.Context, types []string) ([]ecs.InstanceType, error) {
	ret := _m.Called(ctx, types)

	if len(ret) == 0 {
		panic("no return value specified for DescribeInstanceTypes")
	}

	var r0 []ecs.InstanceType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]ecs.InstanceType, error)); ok {
		return rf(ctx, types)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []ecs.InstanceType); ok {
		r0 = rf(ctx, types)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ecs.InstanceType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, types)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeNetworkInterface provides a mock function with given fields: ctx, vpcID, eniID, instanceID, instanceType, status, tags
func (_m *Interface) DescribeNetworkInterface(ctx context.Context, vpcID string, eniID []string, instanceID string, instanceType string, status string, tags map[string]string) ([]*client.NetworkInterface, error) {
	ret := _m.Called(ctx, vpcID, eniID, instanceID, instanceType, status, tags)

	if len(ret) == 0 {
		panic("no return value specified for DescribeNetworkInterface")
	}

	var r0 []*client.NetworkInterface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string, string, string, map[string]string) ([]*client.NetworkInterface, error)); ok {
		return rf(ctx, vpcID, eniID, instanceID, instanceType, status, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, string, string, string, map[string]string) []*client.NetworkInterface); ok {
		r0 = rf(ctx, vpcID, eniID, instanceID, instanceType, status, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client.NetworkInterface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, string, string, string, map[string]string) error); ok {
		r1 = rf(ctx, vpcID, eniID, instanceID, instanceType, status, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeVSwitchByID provides a mock function with given fields: ctx, vSwitchID
func (_m *Interface) DescribeVSwitchByID(ctx context.Context, vSwitchID string) (*vpc.VSwitch, error) {
	ret := _m.Called(ctx, vSwitchID)

	if len(ret) == 0 {
		panic("no return value specified for DescribeVSwitchByID")
	}

	var r0 *vpc.VSwitch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*vpc.VSwitch, error)); ok {
		return rf(ctx, vSwitchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *vpc.VSwitch); ok {
		r0 = rf(ctx, vSwitchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vpc.VSwitch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, vSwitchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetachNetworkInterface provides a mock function with given fields: ctx, eniID, instanceID, trunkENIID
func (_m *Interface) DetachNetworkInterface(ctx context.Context, eniID string, instanceID string, trunkENIID string) error {
	ret := _m.Called(ctx, eniID, instanceID, trunkENIID)

	if len(ret) == 0 {
		panic("no return value specified for DetachNetworkInterface")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, eniID, instanceID, trunkENIID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ModifyNetworkInterfaceAttribute provides a mock function with given fields: ctx, eniID, securityGroupIDs
func (_m *Interface) ModifyNetworkInterfaceAttribute(ctx context.Context, eniID string, securityGroupIDs []string) error {
	ret := _m.Called(ctx, eniID, securityGroupIDs)

	if len(ret) == 0 {
		panic("no return value specified for ModifyNetworkInterfaceAttribute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, eniID, securityGroupIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnAssignIpv6Addresses provides a mock function with given fields: ctx, eniID, ips
func (_m *Interface) UnAssignIpv6Addresses(ctx context.Context, eniID string, ips []netip.Addr) error {
	ret := _m.Called(ctx, eniID, ips)

	if len(ret) == 0 {
		panic("no return value specified for UnAssignIpv6Addresses")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []netip.Addr) error); ok {
		r0 = rf(ctx, eniID, ips)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnAssignPrivateIPAddresses provides a mock function with given fields: ctx, eniID, ips
func (_m *Interface) UnAssignPrivateIPAddresses(ctx context.Context, eniID string, ips []netip.Addr) error {
	ret := _m.Called(ctx, eniID, ips)

	if len(ret) == 0 {
		panic("no return value specified for UnAssignPrivateIPAddresses")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []netip.Addr) error); ok {
		r0 = rf(ctx, eniID, ips)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WaitForNetworkInterface provides a mock function with given fields: ctx, eniID, status, backoff, ignoreNotExist
func (_m *Interface) WaitForNetworkInterface(ctx context.Context, eniID string, status string, backoff wait.Backoff, ignoreNotExist bool) (*client.NetworkInterface, error) {
	ret := _m.Called(ctx, eniID, status, backoff, ignoreNotExist)

	if len(ret) == 0 {
		panic("no return value specified for WaitForNetworkInterface")
	}

	var r0 *client.NetworkInterface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, wait.Backoff, bool) (*client.NetworkInterface, error)); ok {
		return rf(ctx, eniID, status, backoff, ignoreNotExist)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, wait.Backoff, bool) *client.NetworkInterface); ok {
		r0 = rf(ctx, eniID, status, backoff, ignoreNotExist)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.NetworkInterface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, wait.Backoff, bool) error); ok {
		r1 = rf(ctx, eniID, status, backoff, ignoreNotExist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
